apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  creationTimestamp: '2020-08-05T15:05:16Z'
  generation: 2
  name: java-springboot-pipeline-template
  namespace: chatbotdemo
  resourceVersion: '30564759'
  selfLink: >-
    /apis/tekton.dev/v1alpha1/namespaces/chatbotdemo/pipelines/java-springboot-pipeline
  uid: 57fa1dc4-67ab-453d-b0d6-644db26a0998
spec:
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: test
      resources:
        inputs:
          - name: source
            resource: git-source
      taskRef:
        kind: ClusterTask
        name: igc-java-maven-test-v1-01
    - name: build
      resources:
        inputs:
          - name: source
            resource: git-source
        outputs:
          - name: image
            resource: docker-image
      runAfter:
        - test
      taskRef:
        kind: ClusterTask
        name: igc-build-tag-push-v1-01
    - name: deploy
      resources:
        inputs:
          - name: source
            resource: git-source
          - name: image
            resource: docker-image
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: igc-deploy-v1-01
    - name: health
      resources:
        inputs:
          - name: source
            resource: git-source
          - name: image
            resource: docker-image
      runAfter:
        - deploy
      taskRef:
        kind: ClusterTask
        name: igc-health-check-v1-01
    - name: release
      resources:
        inputs:
          - name: source
            resource: git-source
          - name: image
            resource: docker-image
      runAfter:
        - health
      taskRef:
        kind: ClusterTask
        name: igc-helm-package-v1-01
    - name: gitops
      resources:
        inputs:
          - name: source
            resource: git-source
          - name: image
            resource: docker-image
      runAfter:
        - release
      taskRef:
        kind: ClusterTask
        name: igc-gitops-v1-01
