--- 
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata: 
  name: nodejs-ex-s2i-nodejs
spec: 
  resources: 
    - 
      name: git-repo
      type: git
    - 
      name: docker-image
      type: image
  tasks: 
    - 
      name: test
      resources: 
        inputs: 
          - 
            name: source
        resource: git-source
      taskRef: 
        kind: ClusterTask
        name: igc-nodejs-test-v1-01
    - 
      name: build
      resources: 
        inputs: 
          - 
            name: source
            resource: git-source
        outputs: 
          - 
            name: image
            resource: docker-image
      runAfter: 
        - test
      taskRef: 
        kind: ClusterTask
        name: igc-build-tag-push-v1-01
    - 
      name: deploy
      resources: 
        inputs: 
          - 
            name: source
            resource: git-source
        outputs: 
          - 
            name: image
            resource: docker-image
      runAfter: 
        - build
      taskRef: 
        kind: ClusterTask
        name: igc-deploy-v1-01
    - 
      name: health
      resources: 
        inputs: 
          - 
            name: source
            resource: git-source
        outputs: 
          - 
            name: image
            resource: docker-image
      runAfter: 
        - deploy
      taskRef: 
        kind: ClusterTask
        name: igc-health-check-v1-01
    - 
      name: release
      resources: 
        inputs: 
          - 
            name: source
            resource: git-source
        outputs: 
          - 
            name: image
            resource: docker-image
      runAfter: 
        - health
      taskRef: 
        kind: ClusterTask
        name: igc-helm-package-v1-01
    - 
      name: release
      resources: 
        inputs: 
          - 
            name: source
            resource: git-source
        outputs: 
          - 
            name: image
            resource: docker-image
      runAfter: 
        - release
      taskRef: 
        kind: ClusterTask
        name: igc-gitops-v1-01
