apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: nodejs-ex-s2i-nodejs
spec:
  resources:
  - name: git-repo
    type: git
  - name: docker-image
    type: image
  tasks:
  - name: test
    resources:
      inputs:
      - name: source
      resource: git-source
    taskRef:
      name: igc-nodejs-test-v1-01
      kind: ClusterTask
 - name: build
   resources:
     inputs:
     - name: source
       resource: git-source
     outputs:
     - name: image
       resource: docker-image
  runAfter:
  - test
    taskRef:
      name: igc-build-tag-push-v1-01
      kind: ClusterTask
  - name: deploy
    resources:
      inputs:
      - name: source
        resource: git-source
      outputs:
      - name: image
        resource: docker-image
  runAfter:
  - build
    taskRef:
      name: igc-deploy-v1-01
      kind: ClusterTask
  - name: health
    resources:
      inputs:
      - name: source
        resource: git-source
      outputs:
      - name: image
        resource: docker-image
  runAfter:
  - deploy
    taskRef:
      name: igc-health-check-v1-01
      kind: ClusterTask
  - name: release
    resources:
      inputs:
      - name: source
        resource: git-source
      outputs:
      - name: image
        resource: docker-image
  runAfter:
  - health
    taskRef:
      name: igc-helm-package-v1-01
      kind: ClusterTask
  - name: release
    resources:
      inputs:
      - name: source
        resource: git-source
      outputs:
      - name: image
        resource: docker-image
  runAfter:
  - release
    taskRef:
      name: igc-gitops-v1-01
      kind: ClusterTask
























    resources:
      inputs:
      - name: source
        resource: git-repo
      outputs:
      - name: image
        resource: image
    params:
    - name: TLSVERIFY
      value: "false"
  - name: apply-manifests
    taskRef:
      name: apply-manifests
    resources:
      inputs:
      - name: source
        resource: git-repo
    runAfter:
    - build-image
  - name: update-deployment
    taskRef:
      name: update-deployment
    resources:
      inputs:
      - name: image
        resource: image
    params:
    - name: deployment
      value: $(params.deployment-name)
    runAfter:
    - apply-manifests
